IMAGE_INSTALL_append = " mesh-game-loader"
IMAGE_INSTALL_append = " uioctl"
IMAGE_INSTALL_append = " peekpoke"
IMAGE_INSTALL_append = " dynamorio"
IMAGE_INSTALL_append = " wipe"
IMAGE_INSTALL_append = " rng-tools"
IMAGE_INSTALL_append = " libsodium"
